//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdatedNurseryAPIs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class daily_report
    {
        public int id { get; set; }
        public string studies_homework { get; set; }
        public string food { get; set; }
        public string mood { get; set; }
        public System.DateTime created_on { get; set; }
        public int kid_id { get; set; }
    }
}
