//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdatedNurseryAPIs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KidImage
    {
        public int id { get; set; }
        public string image { get; set; }
        public int kid_id { get; set; }
        public System.DateTime created_on { get; set; }
    }
}
